feat: add notification bot
re-nft/notification-discord-bot pull request #1
Opened 2022-09-14 04:53 UTC by seendsouza

2022-09-15 21:02 UTC, nazariyv requested changes

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/constants.py
> +DEFAULT_PAGE_SIZE = 100
I would set it to `1000`, Whoopi is approaching `3000` transactions. The graph supports page size of `1000` no problem.

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/renft.py
> +def get_lending_url(contract: ReNFTContract, lending_id: str):
not a biggie, since it works anyhow, but to be more accurate, we can set the type on `lending_id` to `Union[str, int]`

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/renft.py
> +def get_lending_url(contract: ReNFTContract, lending_id: str):
this is because a bunch of places `data.py` are supplying an `int` as a second argument into this function

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/data.py
> +            msg = (
this and the message on line `80` are essentially the same. We can combine them. For example, something like `f"{nft.name} lent for {'a fee of ' if self.lending.daily_rent_price is not None else ''}"`

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/renft.py
> +def get_profile_url(contract: "ReNFTContract", address: str):
seems like there is no circ dep issue here (since the function above and below are using it explicitly), so we can just drop the double quotes on `ReNFTContract`

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/renft.py
> +    chain_mapping = {
totally up to you, but I would extract this mapping out into constants and call it `EXPLORER_CHAIN_MAPPING`, then we would avoid re-defining it on every call to this function and would have it neatly in consts in case any other code needs it in the future

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/mixins.py
> +    def query_url(self) -> str:
seems to me like `chain` can also be added here as `property` and `abstractmethod`. See `contracts.py` and how we are defining the `chain` function on each class, whereas we could be assigning the property just like `query_url`.

2022-09-15 21:02 UTC, nazariyv commented on notification_discord_bot/contracts.py
> +    name = ETHEREUM_AZRAEL_CONTRACT_NAME
It's a little hard to follow with the mixins. What advantages does this inheritance have over simply inheriting `mixins.EthereumAzraelMixin` directly in the `AzraelContract` class in place of the `BlockChainContract` mixin? We would effectively remove all four classes here. I have searched through the whole of the repository, and the only places where we use `BlockChainContract` mixin is precisely in the definitions of the classes above.

2022-09-15 21:03 UTC, seendsouza commented on notification_discord_bot/constants.py
> +DEFAULT_PAGE_SIZE = 100
Discussed https://discord.com/channels/842471156413235261/972150826103627846/1020069741529927690

2022-09-15 22:03 UTC, seendsouza commented on notification_discord_bot/renft.py
> +    chain_mapping = {
Addressed, but kept in renft because it requires Chain as key

2022-09-15 22:03 UTC, seendsouza commented on notification_discord_bot/mixins.py
> +    def query_url(self) -> str:
Addressed

2022-09-15 22:03 UTC, seendsouza commented on notification_discord_bot/contracts.py
> +    name = ETHEREUM_AZRAEL_CONTRACT_NAME
Addressed

2022-09-15 22:03 UTC, seendsouza commented on notification_discord_bot/renft.py
> +def get_profile_url(contract: "ReNFTContract", address: str):
Addressed

2022-09-15 22:03 UTC, seendsouza commented on notification_discord_bot/data.py
> +            msg = (
Addressed

2022-09-15 22:03 UTC, seendsouza commented on notification_discord_bot/renft.py
> +def get_lending_url(contract: ReNFTContract, lending_id: str):
Addressed

2022-09-25 13:44 UTC, nazariyv commented
We are getting:

```
2780 |:| INFO |:| 2022-09-25 14:42:29.364 |:| Discord is enabled: True
2780 |:| INFO |:| 2022-09-25 14:42:29.365 |:| Twitter is enabled: True
Traceback (most recent call last):
  File "/home/shredder/git/notification-discord-bot/notification_discord_bot/main.py", line 73, in <module>
    main()
  File "/home/shredder/git/notification-discord-bot/notification_discord_bot/main.py", line 67, in main
    check_for_updates(msg_sender)
  File "/home/shredder/git/notification-discord-bot/notification_discord_bot/main.py", line 55, in check_for_updates
    msg_sender.send_discord_message(discord_message)
  File "/home/shredder/git/notification-discord-bot/notification_discord_bot/main.py", line 36, in send_discord_message
    self.discord_webhook.send(embed=msg)
  File "/home/shredder/.cache/pypoetry/virtualenvs/notification-discord-bot-eXHKOFjM-py3.10/lib/python3.10/site-packages/discord/webhook.py", line 989, in send
    return self._adapter.execute_webhook(wait=wait, file=file, files=files, payload=payload)
  File "/home/shredder/.cache/pypoetry/virtualenvs/notification-discord-bot-eXHKOFjM-py3.10/lib/python3.10/site-packages/discord/webhook.py", line 164, in execute_webhook
    maybe_coro = self.request('POST', url, multipart=multipart, payload=data, files=files_to_pass)
  File "/home/shredder/.cache/pypoetry/virtualenvs/notification-discord-bot-eXHKOFjM-py3.10/lib/python3.10/site-packages/discord/webhook.py", line 363, in request
    raise HTTPException(r, response)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.thumbnail.url: Scheme "ipfs" is not supported. Scheme must be one of ('http', 'https').
```

when trying to run this. Must be because it is trying to post ipfs media on twitter.

2022-09-25 15:15 UTC, seendsouza commented
Above comment addressed

2022-11-24 20:39 UTC, merged